# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:         
   - test
  
postman_tests:   
    stage: test
    image: 
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - npm install -g newman-reporter-html      
        - newman run "https://api.getpostman.com/collections/9755093-b6e082a1-4ae7-4c0c-8c82-7d3ef368d214?apikey=PMAK-601af363f1f2f8005c97aa9f-c0ed2c8cfc991f7e141ae4bd813a05fb35"  --env-var "domain=https://qa-api.werner.com" --global-var "base_path=/workday-sapi/v1" --global-var "client_secret=0719DE249dBf400D90495F9B5167b8eA" --global-var "client_id=2720ce1fc49c40ae86e7a5fede8e8f7f" --reporters cli,html --reporter-html-export report.html
    artifacts:
       paths:
        - report.html




