# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test-api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Docker for newman
        run: docker run -v $(pwd)/test:/etc/newman -t postman/newman:lastest run "https://api.getpostman.com/collections/2033404-9f01d861-2ccb-4320-9b60-ee7a2f940171?apikey=PMAK-601af363f1f2f8005c97aa9f-c0ed2c8cfc991f7e141ae4bd813a05fb35" --folder "Leave of Absence" --env-var "domain=https://qa-api.werner.com" --global-var "base_path=employee-xapi/v1" --global-var "client_secret=0719DE249dBf400D90495F9B5167b8eA" --global-var "client_id=2720ce1fc49c40ae86e7a5fede8e8f7f" --reporters cli,junit --reporter-junit-export Results\junitReport.xml

        

      
